FROM sonarqube:9.9.0-community

ADD --chown=sonarqube:sonarqube https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/21.9.0.0/ojdbc8-21.9.0.0.jar /opt/sonarqube/extensions/jdbc-driver/oracle